source/Glimpse.Mvc3.MusicStore.Sample/Controllers/ModelBindingTestsController.cs
using System.Web.Mvc;

namespace MvcMusicStore.Controllers
{
    public class ModelBindingTestsController : Controller
    {
        public ActionResult Index()
        {
            return View("Index", new ComplexType());
        }

        [HttpPost]
        public ActionResult SimplePost(string firstname, string lastname)
        {
            return View("Index", new ComplexType());
        }

        [HttpPost]
        public ActionResult ComplexPost(ComplexType complexType, string additionalSimpleValue)
        {
            return View("Index", new ComplexType());
        }

        public class ComplexType
        {
            public ComplexType()
            {
                this.Name = "Foo";
                this.Another = new SecondLevelComplexType();
            }

            public string Name { get; set; }
            public SecondLevelComplexType Another { get; set; }
        }

        public class SecondLevelComplexType
        {
            public SecondLevelComplexType()
            {
                this.Name = "Bar";
                this.Values = new ThirdLevelComplexType(this.Name);
            }

            public string Name { get; set; }
            public ThirdLevelComplexType Values { get; set; }
        }

        public class ThirdLevelComplexType
        {
            public ThirdLevelComplexType(string valueFor)
            {
                this.Value1 = "Value 1 for " + valueFor;
                this.Value2 = "Value 2 for " + valueFor;
            }

            public string Value1 { get; set; }
            public string Value2 { get; set; }
        }
    }
}

source/Glimpse.Mvc3.MusicStore.Sample/Views/ModelBindingTests/Index.cshtml
@model MvcMusicStore.Controllers.ModelBindingTestsController.ComplexType
@{
    ViewBag.Title = "ModelBindng Tests";
}

@using (Html.BeginForm("SimplePost", "ModelBindingTests", FormMethod.Post))
{
    <label for="FirstName">First name :</label><input type="text" id="FirstName" name="FirstName" value="Foo" /><br/>
    <label for="LastName">Last name :</label><input type="text" id="LastName" name="LastName" value="Bar" />
    <br/>
    <input type="submit" value="Normal post"/>
}

<br/>
<br/>
@using(Html.BeginForm("ComplexPost","ModelBindingTests", FormMethod.Post))
{
    @Html.LabelFor(m=> m.Name, "Name :") 
    @Html.TextBoxFor(m=> m.Name)
    <br/>
    @Html.LabelFor(m=> m.Name, "Another Name :") 
    @Html.TextBoxFor(m=> m.Another.Name)
    <br/>
    @Html.LabelFor(m=> m.Name, "Another Value 1 :") 
    @Html.TextBoxFor(m=> m.Another.Values.Value1) <br/>
    @Html.LabelFor(m=> m.Name, "Another Value 2 :") 
    @Html.TextBoxFor(m=> m.Another.Values.Value2)
    <br/>
    <label for="additionalSimpleValue">Additional simple value :</label>
    <input type="text" id="additionalSimpleValue" name="additionalSimpleValue" value="the additional value"/>
    <br/>
    <br/>
    <input type="submit" value="Normal post with complex type"/>
}